#pragma once


#ifdef _MSC_VER
	#pragma pack(push, 1)
#endif

namespace PUBGSDK {

enum ECoherentUIGTKeys
{
   ECoherentUIGTKeys__LeftMouseButton = 0,
   ECoherentUIGTKeys__RightMouseButton = 1,
   ECoherentUIGTKeys__MiddleMouseButton = 2,
   ECoherentUIGTKeys__ThumbMouseButton = 3,
   ECoherentUIGTKeys__ThumbMouseButton2 = 4,
   ECoherentUIGTKeys__BackSpace = 5,
   ECoherentUIGTKeys__Tab = 6,
   ECoherentUIGTKeys__Enter = 7,
   ECoherentUIGTKeys__Pause = 8,
   ECoherentUIGTKeys__CapsLock = 9,
   ECoherentUIGTKeys__Escape = 10,
   ECoherentUIGTKeys__SpaceBar = 11,
   ECoherentUIGTKeys__PageUp = 12,
   ECoherentUIGTKeys__PageDown = 13,
   ECoherentUIGTKeys__End = 14,
   ECoherentUIGTKeys__Home = 15,
   ECoherentUIGTKeys__Left = 16,
   ECoherentUIGTKeys__Up = 17,
   ECoherentUIGTKeys__Right = 18,
   ECoherentUIGTKeys__Down = 19,
   ECoherentUIGTKeys__Insert = 20,
   ECoherentUIGTKeys__Delete = 21,
   ECoherentUIGTKeys__Zero = 22,
   ECoherentUIGTKeys__One = 23,
   ECoherentUIGTKeys__Two = 24,
   ECoherentUIGTKeys__Three = 25,
   ECoherentUIGTKeys__Four = 26,
   ECoherentUIGTKeys__Five = 27,
   ECoherentUIGTKeys__Six = 28,
   ECoherentUIGTKeys__Seven = 29,
   ECoherentUIGTKeys__Eight = 30,
   ECoherentUIGTKeys__Nine = 31,
   ECoherentUIGTKeys__A = 32,
   ECoherentUIGTKeys__B = 33,
   ECoherentUIGTKeys__C = 34,
   ECoherentUIGTKeys__D = 35,
   ECoherentUIGTKeys__E = 36,
   ECoherentUIGTKeys__F = 37,
   ECoherentUIGTKeys__G = 38,
   ECoherentUIGTKeys__H = 39,
   ECoherentUIGTKeys__I = 40,
   ECoherentUIGTKeys__J = 41,
   ECoherentUIGTKeys__K = 42,
   ECoherentUIGTKeys__L = 43,
   ECoherentUIGTKeys__M = 44,
   ECoherentUIGTKeys__N = 45,
   ECoherentUIGTKeys__O = 46,
   ECoherentUIGTKeys__P = 47,
   ECoherentUIGTKeys__Q = 48,
   ECoherentUIGTKeys__R = 49,
   ECoherentUIGTKeys__S = 50,
   ECoherentUIGTKeys__T = 51,
   ECoherentUIGTKeys__U = 52,
   ECoherentUIGTKeys__V = 53,
   ECoherentUIGTKeys__W = 54,
   ECoherentUIGTKeys__X = 55,
   ECoherentUIGTKeys__Y = 56,
   ECoherentUIGTKeys__Z = 57,
   ECoherentUIGTKeys__NumPadZero = 58,
   ECoherentUIGTKeys__NumPadOne = 59,
   ECoherentUIGTKeys__NumPadTwo = 60,
   ECoherentUIGTKeys__NumPadThree = 61,
   ECoherentUIGTKeys__NumPadFour = 62,
   ECoherentUIGTKeys__NumPadFive = 63,
   ECoherentUIGTKeys__NumPadSix = 64,
   ECoherentUIGTKeys__NumPadSeven = 65,
   ECoherentUIGTKeys__NumPadEight = 66,
   ECoherentUIGTKeys__NumPadNine = 67,
   ECoherentUIGTKeys__Multiply = 68,
   ECoherentUIGTKeys__Add = 69,
   ECoherentUIGTKeys__Subtract = 70,
   ECoherentUIGTKeys__Decimal = 71,
   ECoherentUIGTKeys__Divide = 72,
   ECoherentUIGTKeys__F1 = 73,
   ECoherentUIGTKeys__F2 = 74,
   ECoherentUIGTKeys__F3 = 75,
   ECoherentUIGTKeys__F4 = 76,
   ECoherentUIGTKeys__F5 = 77,
   ECoherentUIGTKeys__F6 = 78,
   ECoherentUIGTKeys__F7 = 79,
   ECoherentUIGTKeys__F8 = 80,
   ECoherentUIGTKeys__F9 = 81,
   ECoherentUIGTKeys__F10 = 82,
   ECoherentUIGTKeys__F11 = 83,
   ECoherentUIGTKeys__F12 = 84,
   ECoherentUIGTKeys__NumLock = 85,
   ECoherentUIGTKeys__ScrollLock = 86,
   ECoherentUIGTKeys__LeftShift = 87,
   ECoherentUIGTKeys__RightShift = 88,
   ECoherentUIGTKeys__LeftControl = 89,
   ECoherentUIGTKeys__RightControl = 90,
   ECoherentUIGTKeys__LeftAlt = 91,
   ECoherentUIGTKeys__RightAlt = 92,
   ECoherentUIGTKeys__LeftCommand = 93,
   ECoherentUIGTKeys__RightCommand = 94,
   ECoherentUIGTKeys__Semicolon = 95,
   ECoherentUIGTKeys__Equals = 96,
   ECoherentUIGTKeys__Comma = 97,
   ECoherentUIGTKeys__Underscore = 98,
   ECoherentUIGTKeys__Period = 99,
   ECoherentUIGTKeys__Slash = 100,
   ECoherentUIGTKeys__Tilde = 101,
   ECoherentUIGTKeys__LeftBracket = 102,
   ECoherentUIGTKeys__Backslash = 103,
   ECoherentUIGTKeys__RightBracket = 104,
   ECoherentUIGTKeys__Quote = 105,
   ECoherentUIGTKeys__Unknown = 106,
   ECoherentUIGTKeys__ECoherentUIGTKeys_MAX = 107,
};}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
